avanzareApp/views.py
from flask import Blueprint, render_template, request, flash, abort, jsonify, redirect, url_for, send_from_directory
from flask_login import login_required, current_user
from .models import Menu, Order, MenuOrder, News
from . import db
import json
import os

# for image uploading
APP_ROOT = os.path.dirname(os.path.abspath(__file__))
target = os.path.join(APP_ROOT, 'images/')
if not os.path.isdir(target):
    os.mkdir(target)
views = Blueprint('views', __name__)


# this function just returns the a specific image based on the name from the directory
@views.route('/upload/<filename>')
def send_image(filename):
    return send_from_directory('images', filename)


# get to edit menu page
@views.route('/edit-menu', methods=['GET'])
def edit_menu():
    # fetch all menu items
    items = Menu.query.all()
    # if user is not logged in and trying to access the page
    if current_user.is_anonymous:
        abort(404, description="Resource not found")
    # make sure page only loads for head chef
    if current_user.email == 'headChef@gmail.com':
        return render_template("edit_menu.html", items=items, user=current_user)
    else:
        flash('Sorry not allowed.', category="error")
        return redirect(url_for('views.user_home'))


# this is the function for the head chef to add any item they want to the menu. There are some requirements like menu
# items cannot have the same name, price must be digits/float, and limited chars for name/description.
@views.route('/add-to-menu', methods=['POST'])
def add_to_menu():
    # get input values from the chef
    name = request.form.get('name')
    price = request.form.get('price')
    description = request.form.get('description')
    menu_type = request.form.get('menu_type')
    gluten_free = request.form.get('gluten_free')
    vegan = request.form.get('vegan')
    tmp_file = request.files.get('file')
    filename = name + '.jpg'
    # if filename empty then do nothing because user doesn't want to change the item image
    if tmp_file.filename != '':
        destination = "/".join([target, filename])
        tmp_file.save(destination)
    else:
        flash('Item image not submitted.', category="error")
        return redirect(url_for('views.edit_menu'))
    # check if there is any item in Menu that already has the name that was entered by chef
    menu_item = Menu.query.filter_by(name=name).first()
    # if menu_item exists then that means the item name is taken already
    if menu_item:
        flash('This dish name already exists.', category="error")
    # test to make sure price is acceptable
    try:
        # if price can't be converted to float then that means there are chars being used that are not digits
        # might be a better way to implement this
        float(price)
        # convert str type price to format it in $0.00 format
        price = "{:,.2f}".format(float(price))
    # (Exception,) stop 'too broad' exception msg
    except (Exception,):
        # refresh page and send error message
        flash('Only enter digits for price.', category="error")
        return redirect(url_for('views.edit_menu'))
    # test to check against any special chars
    special_chars = '`~@#^*()-_=+|[]{};:<>\\/'
    for char in special_chars:
        # check if char is in name/description
        if char in name + description:
            message = 'Some special chars are not permitted such as: ' + char
            flash(message, category="error")
            return redirect(url_for('views.edit_menu'))
    # if all is good then create the item and refresh page
    item = Menu(name=name, price=price, description=description, menu_type=menu_type, gluten_free=gluten_free,
                vegan=vegan, item_image=filename, user_id=current_user.id)
    db.session.add(item)
    db.session.commit()
    return redirect(url_for('views.edit_menu'))


# this function directs the user to their home page, and it also passes their active orders. The past orders can be
# active or clear, so I just filter posts by status not active to get past orders. For efficiency, it might be better
# to change this to one loop that displays the order accordingly
@views.route('/user-home', methods=['GET', 'POST'])
@login_required
def user_home():
    active_orders = Order.query.filter(Order.user_id == current_user.id).filter(Order.is_active == "Active").all()
    # user can view all restaurant's news in user home. This could be changed to show limited random news like in
    # the featured section of the start page, but I'm assuming that there wouldn't be that much news
    # coming from a small family restaurant
    news = db.session.query(News).order_by(News.id.desc()).all()
    db.session.commit()
    return render_template("user_home.html", news=news, active_orders=active_orders, user=current_user)


# this function directs user to the order page
@views.route('/order', methods=['GET', 'POST'])
@login_required
def test_order():
    # fetch all menu items
    items = Menu.query.all()
    return render_template("order.html", items=items, user=current_user)


# Render views order page for chef to see active orders. Active order are orders that are still being prepared
# inactive orders are orders that were completed. In this page inactive orders can be cleared. The idea behind that
# feature is that if it is a new day then you might not want to see inactive orders from the day before
# It could be useful to add feature for chef to see all orders and filter by specific user or date etc. This is going on
# the to do list
@views.route('/view-orders', methods=['POST', 'GET'])
def view_orders():
    active_orders = Order.query.filter(Order.is_active == 'Active').all()
    inactive_orders = Order.query.filter(Order.is_active == 'Inactive').all()
    return render_template('view_orders.html', active_orders=active_orders, inactive_orders=inactive_orders,
                           user=current_user)


# function to deactivate active orders
# it just fetches the order by id and sets the order is_active variable to Inactive and refreshes page
@views.route('/deactivate-order/<int:id>', methods=['POST', 'GET'])
def deactivate_orders(id):
    order = Order.query.filter(Order.id == id).first()
    order.is_active = "Inactive"
    active_orders = Order.query.filter(Order.is_active == 'Active').all()
    inactive_orders = Order.query.filter(Order.is_active == 'Inactive').all()
    db.session.commit()
    return render_template('view_orders.html', active_orders=active_orders, inactive_orders=inactive_orders,
                           user=current_user)


# this sets all inactive orders to clear, so they don't appear in view orders and takes up space
@views.route('/clear-inactive-orders', methods=['POST', 'GET'])
def clear_inactive_orders():
    inactive_orders = Order.query.filter(Order.is_active == 'Inactive').all()
    for item in inactive_orders:
        item.is_active = "clear"
    db.session.commit()
    active_orders = Order.query.filter(Order.is_active == 'Active').all()
    inactive_orders = Order.query.filter(Order.is_active == 'Inactive').all()
    return render_template('view_orders.html', active_orders=active_orders, inactive_orders=inactive_orders,
                           user=current_user)


# a function to create news post and refreshes create news page
@views.route('/create-news', methods=['GET', 'POST'])
@login_required
def create_news():
    # just gets form info and creates a post
    if request.method == "POST":
        title = request.form.get('title')
        text = request.form.get('text')
        news_type = request.form.get('news_type')
        news_post = News(title=title, text=text, news_type=news_type)
        db.session.add(news_post)
        db.session.commit()
        flash('News post created!', category="success")
    news = db.session.query(News).order_by(News.id.desc()).all()
    return render_template("create_news.html", news=news, user=current_user)


# deletes news post using java and jsonify
@views.route('/delete-news-post', methods=['POST', 'GET'])
def delete_news_post():
    news_post = json.loads(request.data)
    news_postId = news_post['news_postId']
    news_post = News.query.get(news_postId)

    if news_post:
        db.session.delete(news_post)
        db.session.commit()
        flash('NEWS POST DELETED!', category="success")
    else:
        flash('error!', category="error")
    return jsonify({})


# this function completes and submits the user's order
@views.route('/complete-order', methods=['POST', 'GET'])
def complete_order():
    # get data from json
    items_list = json.loads(request.data)
    items_list = items_list['values']
    # create new order to save data in
    new_order = Order()
    # set order id to the current user making the order
    new_order.user_id = current_user.id
    # add the rest of the order info
    new_order.is_active = 'Active'
    new_order.total = items_list[1]['total']
    new_order.taxes = items_list[2]['taxes']
    new_order.comment = items_list[3]['comment']
    new_order.name = current_user.first_name
    # save order
    db.session.add(new_order)
    db.session.commit()
    # get the list of items in format name*quantity*price*item_id#name*quantity*price*item_id#....
    items = items_list[0]['string_list'].split('#')
    # the # separates each item
    for item in items:
        # the * separates the item's info
        tmp_item = item.split('*')
        for quantity in range(int(tmp_item[1])):
            # create a menu object to get the rest of the item's info
            menu_item = Menu.query.filter_by(id=tmp_item[2]).first()
            tmp_item_object = MenuOrder()
            # save objects details
            tmp_item_object.name = tmp_item[0]
            tmp_item_object.price = menu_item.price
            tmp_item_object.item_id = menu_item.id
            # create relationship to order
            tmp_item_object.order_id = new_order.id
            db.session.add(tmp_item_object)

avanzareApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Avanzare</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="{{ url_for('static', filename='style.css') }}"
    />
    <title>{% block title%}Home{% endblock %}</title>
</head>
<body style="background: #FFF7EC;">
    <!-- Navbar is shown on every page-->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="#" align="center">
            <img class="img-responsive" src="{{ url_for('views.send_image', filename='logo.jpg') }}" height="100">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                <!-- If user logged in then-->
                {% if user.is_authenticated %}
                    <!-- If user is head chef then these appear in nav-->
                    {% if user.email == "headChef@gmail.com" %}
                        <a class="nav-item nav-link" id="edit_menu" href="/edit-menu">Edit Menu</a>
                        <a class="nav-item nav-link" id="view_orders" href="/view-orders">View Orders</a>
                        <a class="nav-item nav-link" id="create_news" href="/create-news">Create News</a>
                    {% endif %}
                    <a class="nav-item nav-link" id="user_home" href="/user-home">User Home</a>
                    <a class="nav-item nav-link" id="order" href="/order">Order</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                <!-- Not logged in nav links-->
                    <a class="nav-item nav-link" id="menu" href="/">Menu</a>
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="signup" href="/sign-up">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <!-- code to flash messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert alert-danger alter-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% else %}
                <div class="alert alert-success alter-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}
    <br />
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"
    ></script>
</body>
</html>

avanzareApp/templates/create_news.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
<!-- this page is for the chef to create news post that can be seen in the user home and start page -->
<!-- the chef can enter a news title, description, and news type. The chef can delete any news post too -->
<!-- form to get news post details for create_news_post() -->
<form method="POST">
    <h1 align="center"><b>Create news post</b></h1>
    <div class="form-group">
        <label for="title"><b>News Title:</b></label>
        <input
                class="form-control"
                id="title"
                name="title"
                placeholder="ENTER NEWS TITLE"
        />
    </div>
    <label for="text"><b>Text:</b></label>
    <textarea name="text" id="text" class="form-control"></textarea>
    <label for="news_type"><b>News Type:</b></label>
    <select class="selectpicker" id="news_type" name="news_type">
        <option>SALE</option>
        <option>NEW ITEM</option>
        <option>IMPORTANT</option>
    </select>
    <br />
    <br />
    <button type="submit" class="btn btn-primary">Add Item</button>
</form>
<!-- After a news post is submitted create_news_posts() refreshes page to show new news posts -->
<h1 align="center"> Active News </h1>
    <ul class="list-group list-group-flush" id="items">
        {% set print_once = 1 %}
        <!-- Displays the news posts by type -->
        {% for news_type in ["SALE", "NEW ITEM", "IMPORTANT"] %}
            {% if print_once == 1 %}
                <h3 align="center"> {{ news_type }} </h3>
                {% set print_once = 0 %}
            {% endif %}
            {% for news_post in news %}
                {% if news_post.news_type == news_type %}
                      <li class="list-group-item">
                          <b>{{ news_post.title }}</b>
                          <br />
                          {{ news_post.text }}
                          <br />
                          <!-- delete each news post by passing news post id -->
                          <button type="button" class="close" onClick="deleteNewsPost({{ news_post.id }})">
                              <span aria-hidden="true">&times; Delete</span>
                          </button>
                      </li>
                {% endif %}
            {% endfor %}
            {% set print_once = 1 %}
        {% endfor %}
    </ul>
<br />

{% endblock %}

avanzareApp/templates/edit_menu.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
<!-- this page is for the chef to edit the menu. They can add an item and the item must have an input for every field or
 the page will refresh and a warning is flashed. Also, item names are supposed to be unique. The chef can delete and
 edit any item. The page refreshes after any change to see the updated menu -->
<!-- form to get info for add_menu_item() -->
<form action="/add-to-menu" method="POST" enctype="multipart/form-data">
    <h1 align="center">Add an item to the menu</h1>
    <div class="form-group">
        <label for="name"><b>Dish Name</b></label>
        <input
                class="form-control"
                id="name"
                name="name"
                placeholder="ENTER DISH NAME"
                pattern="[a-zaA-Z0-9\s',\.]{2,30}"
        />
    </div>
    <div class="form-group">
        <label for="price"><b>Price</b></label>
        <br />
        <b>$</b>
        <input
                class="currencyinput"
                id="price"
                name="price"
                placeholder="ENTER DISH PRICE"
        />
    </div>
    <div class="form-group">
        <label for="description"><b>Description</b></label>
        <input
                class="form-control"
                id="description"
                name="description"
                placeholder="ENTER DISH DESCRIPTION"
                pattern="[a-zaA-Z0-9\s',&\.]{2,800}"
        />
    </div>
    <label for="gluten_free"><b>Gluten Free Availability</b></label>
    <select class="selectpicker" id="gluten_free" name="gluten_free">
        <option>NO</option>
        <option>GLUTEN FREE</option>
    </select>
    <label for="vegan"><b>Vegan Availability</b></label>
    <select class="selectpicker" id="vegan" name="vegan">
        <option>NO</option>
        <option>VEGAN</option>
    </select>
    <br />
    <label for="menu_type"><b>Menu Type</b></label>
    <select class="selectpicker" id="menu_type" name="menu_type">
        <optgroup label="DINNER MENU" >
            <option>APPETIZERS</option>
            <option>SALADS</option>
            <option>PIZZAS</option>
            <option>PASTAS</option>
            <option>ENTREES</option>
            <option>SIDES</option>
        </optgroup>
        <option>DESSERT MENU</option>
        <option>AFTER DINNER DRINKS</option>
        <option>COCKTAILS</option>
        <optgroup label="BEER">
            <option>BOTTLE</option>
            <option>DRAFT</option>
        </optgroup>
    </select>
    <br />
    <div><b>Item Picture: </b></div>
    <input type="file" name="file" accept="image/*"/>
    <br />
    <br />
    <button type="submit" class="btn btn-primary">Add Item</button>
</form>
<br />
<!-- creates black line around menu -->
<div class="blackLine">
    <br />
    <!-- Since DINNER MENU is the first option I included out of the for loop-->
    <!-- This is one for loop that will create the menu instead of making a for loop for each menu type-->
    <!-- It loops through the menu types and only shows a header for each type once and displays menu item if menu type matches-->
    <h1 class="h1Color" align="center"> DINNER MENU </h1>
    <ul class="list-group list-group-flush" id="items">
        {% for menu in ["APPETIZERS", "SALADS", "PIZZAS", "PASTAS", "ENTREES", "SIDES", "DESSERT MENU", "AFTER DINNER DRINKS", "COCKTAILS", "BOTTLE", "DRAFT"] %}
                {% if menu in ["DESSERT MENU", "AFTER DINNER DRINKS", "COCKTAILS"] %}
                    <h1 class="h1Color" align="center"> {{ menu }} </h1>
                {% else %}
                    <h4 class="menu_type_color" align="center">{{ menu }}</h4>
                    {% if menu == "PIZZAS" %}
                        <p class="menu_type_color" align="center"><i>"ALL PIZZAS ARE HAND TOSSED AND BAKED IN THE WOOD BURNING OVEN"</i></p>
                    {% elif menu == "BOTTLE" %}
                        <h1 class="h1Color" align="center"> BEER </h1>
                        <h4 class="menu_type_color" align="center">{{ menu }}</h4>
                    {% endif %}
                {% endif %}
            <!-- Items are all the menu items, made by headChef -->
            {% for item in items %}
                {% if item.menu_type == menu %}
                    <li class="list-group-item">
                        <div class="container2" >
                            <div class="image">
                                {% set tmp = item.name + '.jpg' %}
                                <img class="img-responsive" src="{{ url_for('views.send_image', filename=tmp) }}" width="200" height="200">
                            </div>
                            <div class="text">
                                <b>{{ item.name }}
                                {% if item.gluten_free == "GLUTEN FREE" %}
                                    <i>{{ "(GF)" }}</i>
                                {% endif %}
                                {% if item.vegan == "VEGAN" %}
                                    <i>{{ "(V)" }}</i>
                                {% endif %}
                                <!--item.price is a float so needs to be converted to string to display $ format-->
                                {% set tmp = "$" + (item.price | string) %}
                                {{ tmp }}</b>
                                <br />
                                <i>{{ item.description }}</i>
                                <!-- shows a button to edit and delete menu item by passing id to corresponding function -->
                                <div style="padding-top: 20px;">
                                    <form action="/delete-menu-item/{{ item.id }}" method="POST">
                                        <button class="btn-del" type="submit">Delete</button>
                                    </form>
                                    <button id="edit_{{ item.id }}"
                                            class="show btn-edit"
                                            onClick="blueprint({{ item.id }})">Edit</button>
                                </div>
                            </div>
                        </div>
                        <div id="hidden_{{ item.id }}" class="only_one" hidden><div class="edit_page">{% include 'edit_page_blueprint.html' %}</div></div>
                    </li>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </ul>
    <br />
</div>
<br />
<br />

{% endblock %}

avanzareApp/templates/edit_page_blueprint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<button id="edit_button_{{ item.id }}" onClick="closeBlueprint({{ item.id }})" class="btn-del" style="float: right;">Close Edit</button>
<form action="/edit-menu-item/{{ item.id }}" method="POST" enctype="multipart/form-data">
    <h3 align="center">Edit menu information</h3>
    <label for="name"><b>Name: <i>{{item.name}}</i></b></label>
    <input
           class="form-control"
           id="name"
           name="name"
           value="{{item.name}}"
           pattern="[a-zaA-Z\s',\.]{2,30}"
           required>
    <label for="price"><b>Price: <i>{{item.price}}</i></b></label>
    <br />
    <b>$</b>
    <input
           class="currencyinput"
           id="price"
           name="price"
           value="{{item.price}}"
           pattern="\d{1,3}(,\d{3})*(\.\d+)"
           required>
    <br />
    <label for="description"><b>Description: <i>{{item.description}}</i></b></label>
    <textarea
                class="form-control"
                id="description"
                name="description"
                pattern="[a-zaA-Z\s',\.]{2,800}"
                required>{{item.description}}</textarea>

    <label for="gluten_free"><b>Gluten Free Availability: <i>{{ item.gluten_free }}</i></b></label>
    <select class="selectpicker selectLength" id="gluten_free" name="gluten_free">
        <option selected>{{ item.gluten_free }}</option>
        {% if item.gluten_free == 'GLUTEN FREE' %}
            <option>NO</option>
        {% else %}
            <option>GLUTEN FREE</option>
        {% endif %}
    </select>
    <br />
    <label for="vegan"><b>Vegan Availability: <i>{{ item.vegan }}</i></b></label>
    <select class="selectpicker selectLength" id="vegan" name="vegan">
        <option selected>{{ item.vegan }}</option>
        {% if item.vegan == 'VEGAN' %}
            <option>NO</option>
        {% else %}
            <option>VEGAN</option>
        {% endif %}
    </select>
    <br />
    <label for="menu_type"><b>Menu Type: <i>{{ item.menu_type }}</i></b></label>
    {% set dinner_menu = ['APPETIZERS', 'SALADS', 'PIZZAS', 'PASTAS', 'ENTREES', 'SIDES'] %}
    {% set other_menus = ['DESSERT MENU', 'AFTER DINNER DRINKS', 'COCKTAILS', 'BEER'] %}
    <select class="selectpicker selectLength" id="menu_type" name="menu_type">
        <optgroup label="DINNER MENU">
            {% for menu_type in dinner_menu %}
                {% if menu_type == item.menu_type %}
                    <option selected>{{ menu_type }}</option>
                {% else %}
                    <option>{{ menu_type }}</option>
                {% endif %}
            {% endfor %}
        </optgroup>
        {% for menu_type in other_menus %}
            {% if menu_type == 'BEER' %}
                <optgroup label="BEER">
                    {% if menu_type == item.menu_type %}
                        <option selected>BOTTLE</option>
                    {% else %}
                        <option>BOTTLE</option>
                    {% endif %}
                    {% if menu_type == item.menu_type %}
                        <option selected>DRAFT</option>
                    {% else %}
                        <option>DRAFT</option>
                    {% endif %}
                </optgroup>
            {% else %}
                {% if menu_type == item.menu_type %}
                    <option selected>{{ menu_type }}</option>
                {% else %}
                    <option>{{ menu_type }}</option>
                {% endif %}
            {% endif %}
        {% endfor %}
    </select>
    <br />
    <label for="file"><b>Item Picture:</b></label>
    <input type="file" id="file" name="file" accept="image/*"/>
    <br />
    {% set tmp = item.name + '.jpg' %}
    <label for="previous_image"><b>Previous Image:</b></label>
    <img id="previous_image" class="img-responsive image" src="{{ url_for('views.send_image', filename=tmp) }}" width="200" height="200">
    <br />
    <button type="submit" class="btn-add">Edit Item</button>
</form>
<br />
</body>
</html>

avanzareApp/templates/login.html
{% extends "base.html" %}
{% block title%}Login{% endblock%}
{% block content %}
<!-- this page is for a user to log in and make an order or view past orders. Users are directed to user_home after
 logging in -->
<!-- form to pass info to login() in auth -->
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="ENTER EMAIL"
        />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input
                type="password"
                class="form-control"
                id="password"
                name="password"
                placeholder="ENTER PASSWORD"
        />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
<br />
<div>
    <!-- this note is only for people who want to view and test this project -->
    <p>NOTE: this is the info for "ADMIN" account</p>
    <p>Email: headChef@gmail.com</p>
    <p>Password: pasta123</p>
</div>
<br/>
{% include "footer.html" %}
{% endblock %}

avanzareApp/templates/sign_up.html
{% extends "base.html" %}
{% block title%}Sign Up{% endblock%}

{% block content %}
<!-- users can sign up for an account and after are directed to the login page. This can be changed to direct them to
the user's home page -->
<!-- form to pass variables to sign_up() there are some p tags to describe email and password specifications -->
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <p>NO SPECIAL CHARS ALLOWED EXCEPT(@ AND .)</p>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="ENTER EMAIL"
        />
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input
                type="text"
                class="form-control"
                id="firstName"
                name="firstName"
                placeholder="ENTER FIRST NAME"
        />
    </div>
    <p>PASSWORD MUST BE AT LEAST 7 CHARACTERS</p>
    <div class="form-group">
        <label for="password1">Password</label>
        <input
                type="password"
                class="form-control"
                id="password1"
                name="password1"
                placeholder="ENTER PASSWORD"
        />
    </div>
    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
                type="password"
                class="form-control"
                id="password2"
                name="password2"
                placeholder="CONFIRM PASSWORD"
        />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<br />
<div>
    <!-- this is only here for people who want to check out the project -->
    <p>NOTE: this is the info for "ADMIN" account</p>
    <p>Email: headChef@gmail.com</p>
    <p>Password: pasta123</p>
</div>
<br/>
{% include "footer.html" %}
{% endblock %}